### PR TITLE
added build workflow

### PR DESCRIPTION
**Pull request by paspo**
This PR is for enabling some github actions for:

(on every tag)

- building the binaries for four architectures (amd64, aarch64, i386, armv7), all statically linked
- preparing a draft github release with the binaries attached
- building and publishing four docker images, one for each arch
- building and publishing a manifest for a combined docker image, with `latest` tag

To make this work, a **repo admin** has to add some docker secrets:

- **DOCKER_IMAGE** should be the target image name on docker hub (e.g. `rustdesk/rustdesk-server` )
- **DOCKER_USERNAME** is the username you normally use to login at [docker hub](https://hub.docker.com/) 
- **DOCKER_PASSWORD** is a token you should create (on [docker hub](https://hub.docker.com/)  ) under "account settings / security" with read/write access

I tested the images (temporary published [here](https://hub.docker.com/r/paspo/rustdesk-server/tags) ) and everything seems to work. We need more tests, just to be sure.

### CODE REVIEW

**Comment by paspo** [comment]
I just tested synology installation, and it worked at first try!

I downloaded the image, started the wizard, then choosed the standard bridge networking, changed the RELAY environment variable to something significant, added a `/data` volume and assigned the correct port numbers (because if you leave them to "automatic", synology will choose some random ones.

**Comment by paspo** [comment]
Why are you confused, @rustdesk ? 
This is expected behavior of this PR: you use `rustdesk/rustdesk-server:latest` docker image everywhere and should run without much effort. And the image is build automagically...

**Comment by rustdesk** [comment]
Ok, then I am confused. :)

**Comment by rustdesk** [comment]
When is this action triggered?

**Comment by rustdesk** [comment]
`at 10:00 on every tuesday` will be `latest` tag image?

**Comment by paspo** [comment]
> `at 10:00 on every tuesday` will be `latest` tag image?

This builds only latest, I'm not using specific version tag.
I saw that on the docker hub you have only the latest tag, so I acted accordingly.
We can always change that.
In fact, I think it's best to keep every version on docker hub, so one can choose a specific version.

**Comment by paspo** [comment]
Also, the 'cron rebuild' is to keep up with possible base image updates, it's not strictly needed, especially with busybox.

**Comment by rustdesk** [comment]
As I know, we can not create docker tag from command line.

**Comment by paspo** [comment]
> As I know, we can not create docker tag from command line.

no need.

You just tag a specific git commit with '1.0.9'

**Comment by rustdesk** [comment]
Can our current users upgrade seamlessly without any effort?

**Comment by rustdesk** [comment]
Or say, if old command work?

```
sudo docker run --name hbbs -p 21115:21115 -p 21116:21116 -p 21116:21116/udp -p 21118:21118 -v `pwd`:/root -it --net=host --rm rustdesk/rustdesk-server hbbs -r <relay-server-ip[:port]> 
sudo docker run --name hbbr -p 21117:21117 -p 21119:21119 -v `pwd`:/root -it --net=host --rm rustdesk/rustdesk-server hbbr 
```

**Comment by paspo** [comment]
old command doesn't works for these reasons:

- we now have a SINGLE container
- we have now an init system (s6-overlay) instead of executing a command (to address https://github.com/rustdesk/rustdesk-server/issues/36) so we don't use a start command and process 1 is now the init system, not a process
- `--net=host` is not used (because it's not safe to expose the whole container, we expose single ports)
- we now specify the relay with an environment variable

so the resulting command is:

```bash
docker run --name rustdesk-server \
  -p 21115:21115 -p 21116:21116 -p 21116:21116/udp \
  -p 21117:21117 -p 21118:21118 -p 21119:21119 \
  -e "RELAY=rustdeskrelay.example.com" \
  -v "$PWD/data:/data" -d rustdesk/rustdesk-server
```

If you want to test before accepting the PR, you can use `paspo/rustdesk-server:latest` for now.

**Comment by paspo** [comment]
also, the docker-compose get simplified:

```yaml
version: '3'

services:
  rustdesk-server:
    container_name: rustdesk-server
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21117:21117
      - 21118:21118
      - 21119:21119
    image: rustdesk/rustdesk-server:latest
    environment:
      - "RELAY=rustdesk.example.com:21117"
    volumes:
      - ./data:/data
    restart: unless-stopped
```

**Comment by rustdesk** [comment]
Then we should create another tag, rather than override old one.

**Comment by paspo** [comment]
Some ideas for the future:

- an environment flag to implement the `-k _` parameter for hbbs
- an environment flag to disable hbbs (suppose you want a single instance of hbbs and multiple distributed hbbr), if that makes sense
- .deb (.rpm or other) package generation

**Comment by rustdesk** [comment]
Let's make two tags, the `latest` remains, and we use a new name for your one with SIGINT fix.

**Comment by paspo** [comment]
I added:

- custom build tag (now it's `devel` but can easily be changed to something else
- docker images get tagged with git tag also

so if we commit with tag '1.2.3' we get these docker images:

- amd64 arch with tags: `1.2.3-amd64` and `devel-amd64`
- i386 arch with tags: `1.2.3-i386` and `devel-i386`
- arm64v8 arch with tags: `1.2.3-arm64v8` and `devel-arm64v8`
- armv7 arch with tags: `1.2.3-armv7` and `devel-armv7`
- multiarch image with tags `1.2.3` and `devel`

that way, when a new tag is pushed (let's say `1.2.4`) all the `1.2.3` tags remains untouched and all the `devel` tags gets updated

**Comment by paspo** [comment]
implemented an environment flag to add the -k _ parameter for hbbs

command is now:

```bash
docker run --name rustdesk-server \
  -p 21115:21115 -p 21116:21116 -p 21116:21116/udp \
  -p 21117:21117 -p 21118:21118 -p 21119:21119 \
  -e "RELAY=rustdeskrelay.example.com" \
  -e "ENCRYPTED_ONLY=1" \
  -v "$PWD/data:/data" -d rustdesk/rustdesk-server
```

docker-compose:

```yaml
version: '3'

services:
  rustdesk-server:
    container_name: rustdesk-server
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21117:21117
      - 21118:21118
      - 21119:21119
    image: rustdesk/rustdesk-server:latest
    environment:
      - "RELAY=rustdesk.example.com:21117"
      - "ENCRYPTED_ONLY=1"
    volumes:
      - ./data:/data
    restart: unless-stopped
```

**Comment by paspo** [comment]
> I'm thinking that the new image could be under `rustdesk/rustdesk`, 

I like that idea. A lot.

And it's possible to implement this with 1 line of changes and a different github secret.

At the moment we know nothing about future plans, I mean, about API and web interface; it's probably best to wait for @rustdesk opinion on the matter, because we'd have to decide if these features will be included in the same image or not.

**Comment by rustdesk** [comment]
> like

I like also if I am not the maintainer, but we stand in different positions. Can't we make this new image back compatible to old image? For example, we turn on the new feature with some option or env variable explicitly.

**Comment by rustdesk** [comment]
> about API and web interface

It is a hard choice.

**Comment by paspo** [comment]
> > like
> 
> I like also if I am not the maintainer, but we stand in different positions. Can't we make this new image back compatible to old image? For example, we turn on the new feature with some option or env variable explicitly.

I'm sorry, but I don't understand: on every comment by @rustdesk I see the badge "owner", that means that you're in charge. If it is not, who's taking decisions? 

Whoever it is, it's best to include him/her in this process.

**Comment by paspo** [comment]
> > about API and web interface
> 
> It is a hard choice.

can you explain?

**Comment by rustdesk** [comment]
> decisions

I am the decision maker.

**Comment by mini-bomba** [comment]
> Can't we make this new image back compatible to old image? For example, we turn on the new feature with some option or env variable explicitly.

This new image has a lot of improvements over the old one, and I think it justifies having the changes in the way the container works. 

I'm unsure what backward compatibility you're concerned about - The data directory actually is backwards compatible - we didn't change the server binaries which use it - we only changed where it is mounted at in the container.
If users had any scripts that managed the containers, they shouldn't have issues with updating them to support the new images. It might even make them simpler, since now we only need to run one container instead of two.
If users were able to figure out how to run the old images, they should also be able to figure out how to run the new images. We still use docker, the only things that change are the parameters. The use of environment variables instead of command line parameters makes it simpler for users to understand what data they need to enter.

I also don't think docker auto-updates images, so the only time when the user would have to change something is when they decide to do an update of the container.
And the update process shouldn't be difficult. It would likely only require them to change the command parameters they use.

Last thing: I'm not sure if putting hbbr and hbbs on different machines should be supported. If it is something that should be supported then I think we should add an environment variable to only enable one of the components.

**Comment by rustdesk** [comment]
Allow me some time to digest. Very good job.

**Comment by timgblack** [comment]
If RustDesk is following standard semantic versioning, breaking API changes require a new major version - when released, the new Docker image would be 2.0.0, and people should expect breaking changes to their scripts when they upgrade.

What about providing three images - rustdesk-hbbr, rustdesk-hbbs, and rustdesk-server?

**Comment by paspo** [comment]
With this last set of modifications (after a constructive talk with @rustdesk ) I added:

- automatic build, tag and push of these "s6" docker images AND the "classic" docker images
- the "classic" docker images are built the same way as before and follow the usual docker tag naming schema
- the "s6" docker images, on the other hand, have distinct tag based on architecture, git tag (software version), and major version
- I updated the README

Note: in the readme I indicated as an example version '2.0.0'. If you choose to use a different version number, it's best to update the readme also.

Please, BEFORE accepting this PR:

- test the images, by building yourself or by using the temporary images from [here (classic)](https://hub.docker.com/r/paspo/rustdesk-server-classic) and [here (s6)](https://hub.docker.com/r/paspo/rustdesk-server)
- @rustdesk update the repository with the required secrets ([see initial comments of build.yaml file](https://github.com/rustdesk/rustdesk-server/pull/43/files#diff-d0777657fa3fd81d23aaf7273e58aee453b04e67882517900c56daeef9b3e4c1)), otherwise build will fail
- remember that the build is triggered by a GIT TAG, having the format of 'v1.2.3' or '1.2.3'

Waiting for comments

**Comment by rustdesk** [comment]
Got it, Thanks, I will test it.

**Comment by rustdesk** [comment]
We finally reach an agreement. :)

**Comment by rustdesk** [comment]
question, why musl instead gnu?

**Comment by rustdesk** [comment]
> question, why musl instead gnu?

I got the answer https://stackoverflow.com/questions/31770604/how-to-generate-statically-linked-executables/31778003#31778003

**Pull request merged**
