### PR TITLE
test new Dockerfile with s6-overlay

### PR DESCRIPTION
**Pull request by paspo**
I created a new Dockerfile which aims to manage `hbbr` and `hbbs` services with [s6-overlay](https://github.com/just-containers/s6-overlay).

At the moment, since I don't know the details of your CD system, this doesn't fetch the precompiled binaries, but rather it builds them itself using a `rust:alpine` container.

### CODE REVIEW

**Comment by paspo** [comment]
The final release container is build against the `busybox` image, which is even lighter than `alpine`.

Both services are running with `/data` as *workdir* so this is the only necessary volume export.

You can specify the relay using the `RELAY` environment variable.

**Comment by rustdesk** [comment]
Thanks

**Comment by paspo** [comment]
@rustdesk we were supposed to talk about that, before merging...

I mean: there are a couple of points I would like to address:

- multi arch builds
- put all docker images (for a specific tag) in a single docker image (with manifest) so that you can always use `rustdesk/rustdesk-server:latest` and the host will choose the right image for the current architecture
- maybe some info on the build system would help

At the moment this is building from source, and it's targeting the *latest* branch. Ideally you want the build system to build on a specific branch/tag.

I think we should start from the last point, the build system. What are you currently using?

**Comment by rustdesk** [comment]
> * in a single docker image

I do not know if it is convenient to build a single docker image for different archs with Rust cross compile on one machine.

**Comment by rustdesk** [comment]
> branch/tag

Latest is ok, rustdesk-server won't be updated frequenently as client.

**Comment by rustdesk** [comment]
Honestly, I have no such experience either, or our CI/CD is written by contributors.

**Comment by rustdesk** [comment]
> I think I can give github a try

Thanks

**Comment by mini-bomba** [comment]
Honestly, you should've marked this pull request as a draft if it wasn't ready yet. I guess it's time to open another draft PR with more changes...
Also, I've found this page about publishing docker images from GH Actions: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
Another thing: I think it would be wise to remove source code from the image, to cut down on the image size.

**Comment by paspo** [comment]
> Honestly, you should've marked this pull request as a draft if it wasn't ready yet. 

You're right... as I said, github is not my main tool...

> Another thing: I think it would be wise to remove source code from the image, to cut down on the image size.

That was the point of the discussion. I didn't know how the binaries were made (now I know: manually), and I needed to build the docker images starting from the binaries. I really didn't think to use this Dockerfile as-is (because, you know, minutes of build time), the draft-marking would've been a real blessing.

I'll work on multiarch rust compile with github actions, then I'll add the image creation. When everything works (on my fork), I'll PR.

**Pull request merged**
